# Generated by Django 4.2 on 2023-05-03 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_Rol', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Rol')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre del Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_Usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Ususario')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo del Usuario')),
                ('clave', models.CharField(max_length=16, verbose_name='Clave del Usuario')),
                ('estatus', models.CharField(max_length=2, verbose_name='Esta activo o no')),
                ('rut', models.CharField(max_length=11, verbose_name='Rut del usuario')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
        ),
    ]
